baseURL = "https://mafyouit.tech"
languageCode = "fr-fr"
title = "Mafyou IT"
copyright = "Copyright © 2022, Mathieu Dupleix; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Mafyou"
  description = "Conseils & Formations"
  keywords = "informatique;formations;conseils;"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayRecent = true
  recentMax = 2
  mail = "mdupleix.pro@hotmail.com"
  phone = "0615042445"
  formspreeID = "f/mgedojyb"

[menu]
  [[menu.main]]
    name = "Accueil"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "Prix"
    pre = "<i class=\"fa fa-money fa-ms\"></i>"
    url = "/prices/"
    weight = -8
  #[[menu.main]]
    #name = "tags"
    #pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    #url = "/tags"
    #weight = -7 
  #[[menu.main]]
    #name = "Github"
    #pre = "<i class=\"fab fa-github fa-ms\"></i>"
    #url = "https://github.com/Mafyou"
    #weight = -6 
  #[[menu.main]]
    #name = "RSS"
    #pre = "<i class=\"fas fa-rss fa-ms\"></i>"
    #url = "/index.xml"
    #weight = -4 
  [[menu.main]]
    name = "Contact"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/contact"
    weight = -1 
